name: 'Node Install'
description: 'Setup Node.js and install dependencies'

inputs:
  pnpm-version:
    description: 'The version of pnpm to install'
    required: false
    default: '10'
  node-version:
    description: 'The version of Node.js to use'
    required: false
    default: 'lts/*'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@d648c2dd069001a242c621c8306af467f150e99d
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Set Node.js version to ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      env:
        HUSKY: '0'
